### ISSUE TITLE
Ensure JacketSE compatible with openmdao 0.10.3.2 is fully up to date on github and integrated with wisdem jacketse assemblies

### ISSUE THREAD

**Issue by dykesk** [WISDEM/JacketSE#3]
JacketSE has been updated quite a lot off line; need to make sure its updated on github and that the assemblies for WISDEm using the jacket are updated as well (note: may need to check on the status of offline updates for pyframe3DD that need to be updated to github as well)

**Comment by dykesk** [comment]
also make sure JacketSE directory structure and files reflect the common SE repository structure (see TowerSE for example)

**Comment by kilojoules** [comment]
I moved Casey's pySubDyn changes to a separate JacketSE branch. Maybe we should move Casey's CommonSE changes there and revert to the previous CommonSE.
